Add support for windows 64
conda-forge/bfg-feedstock pull request #2
Opened 2018-08-16 10:48 UTC by melund

The openjdk conda package has support win64 so there is no reason this shouldn't work for win64 as well.

2018-08-16 10:48 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-03-07 11:05 UTC, carlodri requested changes
thanks for this PR!

you also need to rerender the recipe so that the windows builds get triggered

2019-03-07 11:05 UTC, carlodri commented on recipe/meta.yaml
> +  skip: True  # [win32]
```suggestion

```

2019-03-07 11:05 UTC, carlodri commented on recipe/meta.yaml
> +  skip: True  # [win32]
you can completely remove this line since only win64 is supported

2019-03-07 11:05 UTC, carlodri commented on recipe/meta.yaml
>    number: 0
```suggestion
  number: 1
```

increase the build number

2019-03-07 11:05 UTC, carlodri commented
@JohnGreeley if you wish you can add me as a maintainer

2019-03-07 11:21 UTC, melund commented
@conda-forge-admin please rerender

2019-03-07 11:49 UTC, carlodri approved these changes

2019-03-07 11:49 UTC, carlodri commented
thanks @melund! We need to wait for @JohnGreeley...

2019-03-08 08:43 UTC, carlodri commented
@conda-forge/core sorry for pinging, but I need this package in my workflow: can someone please merge? I can also be added as maintainer if desired.

2019-03-08 12:50 UTC, isuruf commented
Let's give @JohnGreeley a few more days to review.

2019-03-08 17:54 UTC, scopatz commented
This was opened back in August.  I'd be happy to merge now if you wanted to add either @carlodri or @melund to the maintainers list

2019-03-08 20:05 UTC, carlodri commented
@scopatz that was why I opted to ping core, and also because @JohnGreeley seemed to be fairly inactive here on GH in the last years, at least from what you can tell from his profile. As I said, I'm happy to help in the maintenance if you want to add me, it's not a big chore and it would revive a very useful feedstock.

2019-03-08 20:59 UTC, scopatz commented
It would be great if you could add yourself 😉

2019-03-08 21:04 UTC, carlodri commented
@scopatz sure, will make a PR in a moment, sorry (I thought you intended to merge this PR after adding my name in it...)!

2019-03-08 21:38 UTC, scopatz commented
You should be a maintainer now / soon @carlodri :) once you are added, feel free to merge this!

2019-03-08 21:52 UTC, carlodri commented
Thanks!

2019-03-11 08:30 UTC, carlodri commented
@conda-forge-admin, please rerender

2019-03-11 08:31 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-webservice.

I tried to re-render for you, but it looks like there was nothing to do.

2019-03-11 08:45 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2019-03-11 10:23 UTC, merged